name: JUnit tests 

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Download JUnit and Hamcrest
      run: |
        wget https://repo1.maven.org/maven2/junit/junit/4.13.1/junit-4.13.1.jar
        wget https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
    - name: Compile Java files
      run: |
        javac -d bin -sourcepath src -cp junit-4.13.1.jar:hamcrest-core-1.3.jar -g src/test/*.java
    - name: Run JUnit tests
      run: |
        java -cp bin:junit-4.13.1.jar:hamcrest-core-1.3.jar org.junit.runner.JUnitCore test.TestSuite